// <auto-generated />
namespace Reptile.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class 新增資料表 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(新增資料表));
        
        string IMigrationMetadata.Id
        {
            get { return "202103070826025_新增資料表"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
